### ISSUE TITLE
Explore allowing piped input?

### ISSUE THREAD

**Issue by courajs** [courajs/mkchoice#5]
Currently we're getting the tty for the current process by spawning `/usr/bin/tty`.
But I just learned about `/dev/tty`, which is always the tty for the controlling process. We can probably just use that! Then we should be able to pipe both in and out, and still write the prompt directly to the terminal

**Comment by courajs** [comment]
See https://github.com/TooTallNate/ttys/blob/master/index.js

**Comment by courajs** [comment]
Seems like that file exists if you are running a tty context, and doesn't if you aren't.

With a tty:
```
🚀 thing$ docker run --rm -it node node -e "const fs = require('fs'); const tty = require('tty'); let fd = fs.openSync('/dev/tty', 'r'); console.log('is it?', tty.isatty(fd))"
is it? true
```
Without:
```
🚀 thing$ docker run --rm node node -e "const fs = require('fs'); const tty = require('tty'); let fd = fs.openSync('/dev/tty', 'r'); console.log('is it?', tty.isatty(fd))"
fs.js:652
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENXIO: no such device or address, open '/dev/tty'
    at Object.fs.openSync (fs.js:652:18)
    at [eval]:1:67
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at Object.runInThisContext (vm.js:116:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:573:30)
    at evalScript (bootstrap_node.js:435:27)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:578:3
```

**Comment by courajs** [comment]
Added in https://github.com/courajs/mkchoice/commit/6e72aef248fd8570ec491126eae003a5263f7cfd
